import React, { useState, useContext, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "./../../styles/Home.module.scss";
import Header from "./../../components/Header/Header";
import LoginStack from "./../../components/LoginStack/LoginStack";
import LogoutStack from "./../../components/LogoutStack/LogoutStack";
import { UserContext } from "./../../app/state/contexts/userContext";
import { getCookie, setCookie } from "cookies-next";
export default function Home() {
  const [state, dispatch] = useContext(UserContext);
  const [id, setId] = useState("");
  useEffect(() => {
    setId(localStorage.getItem("uad-cache"));
    if (getCookie("token")) {
      dispatch({ type: "redirect-dashboard" });
      setTimeout(() => {
        setCookie("token", null);
        dispatch({ type: "redirect-dashboard-false" });
      }, 1000);
    }
    console.log("State in user index:", state);
  }, []);
  if (state == undefined) {
    return <></>;
  }
  return (
    <div>
      <Head>
        <title>MRKPay.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className={styles.app}>
          {!state.loggedIn ? (
            <LogoutStack setUserData={dispatch} />
          ) : (
            <LoginStack />
          )}
        </div>
      </main>
    </div>
  );
}
