import React, { useState, useContext, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Header from "../components/Header/Header";
import LoginStack from "../components/LoginStack/LoginStack";
import LogoutStack from "../components/LogoutStack/LogoutStack";
import { UserContext } from "./../app/state/contexts/userContext";
import Ad from "./../components/Ad/Ad";
import Timer from "./../components/Timer/Timer";
import News from "./../components/News/News";
export default function Home() {
  useEffect(() => {
    localStorage.setItem("mozilla-support-status", "na");
    localStorage.removeItem("status");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>MRKPay.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>

      <main className={styles.container}>
        <div className={styles.app}>
          <img
            src="/assets/modi.jpg"
            alt="pm-image"
            style={{ width: "100%" }}
          />
          {/* <Timer /> */}
          <News />
        </div>
      </main>
    </div>
  );
}
